; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c6]
platform = espressif32@6.9.0
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
    -DCONFIG_LOG_DEFAULT_LEVEL_DEBUG=1
    -DIDF_VER=\"5.3.1\"
build_unflags = 
upload_speed = 921600
extra_scripts = 
    extra_script.py
    fix_git_refs.py
lib_deps = arduino-libraries/SD@^1.3.0
