// Stable sidebar: Hub + SK (with safe sections) + EN placeholder
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'doc', id: 'KNIFE_HOME_SK', label: '🏠 Domov' },
    {
      type: 'category',
      label: '7Ds',
      link: { type: 'doc', id: 'SK_7DS_HOME' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'sk/7Ds' }],
    },
    {
      type: 'category',
      label: 'KNIFES',
      link: { type: 'doc', id: 'SK_KNIFES_HOME' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'sk/knifes' }],
    },
    {
      type: 'category',
      label: 'English',
      link: { type: 'doc', id: 'KNIFE_HOME_EN' },
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'en' }],
    },
  ],
};

export default sidebars;
