import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🆘 HELP (SK)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/help',
        },
      ],
    },

    {
      type: 'category',
      label: '🔪 KNIFE (SK)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/knifes',
        },
      ],
    },

    {
      type: 'category',
      label: '🧭 7Ds (SK)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/7ds',
        },
      ],
    },

    {
      type: 'category',
      label: '⚙️ SDLC (SK)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/sdlc',
        },
      ],
    },

    {
      type: 'category',
      label: '🎓 STHDF (SK)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/sthdf',
        },
      ],
    },

    {
      type: 'category',
      label: '📐 Q12 (SK)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sk/q12',
        },
      ],
    },

    // THESIS necháme zakomentované, kým nebude template pripravený
    // {
    //   type: 'category',
    //   label: '📄 Thesis (SK)',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'sk/thesis',
    //     },
    //   ],
    // },
  ],
};

export default sidebars;