import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Hardware',
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/hardware',
        },
      ],
    },
    {
      type: 'category',
      label: '⚡ Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/features',
        },
      ],
    },
    {
      type: 'category',
      label: '💻 Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/architecture',
        },
      ],
    },
  ],
};

export default sidebars;
