// sidebars.ts – locale-aware sidebars for multi-docs (SK/EN) using one file
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Docusaurus sets this when building each locale: 'sk' or 'en'
const LOCALE = process.env.DOCUSAURUS_CURRENT_LOCALE || 'sk';

/**
 * For SK we have 7Ds and KNIFES trees.
 * For EN we currently have no content → provide a minimal sidebar
 * to avoid "empty category" errors.
 */

const SK_SIDEBAR = [
  // Home doc: requires docs/sk/index.md with id: KNIFE_HOME (slug: "/")
  { type: 'doc', id: 'KNIFE_HOME_SK', label: '🏠 Domov' },

  // 7Ds category: link to index (works even if there are no children yet)
  {
    type: 'category',
    label: '7Ds',
    link: { type: 'doc', id: 'sk/7Ds/index' },
    collapsed: false,
    // If you later add subpages under docs/sk/7Ds, switch to autogenerated:
    // items: [{ type: 'autogenerated', dirName: '7Ds' }],
    items: [],
  },

  // KNIFES: autogenerated from docs/sk/knifes (safe if directory exists)
  {
    type: 'category',
    label: 'KNIFES',
    link: { type: 'doc', id: 'sk/knifes/index' },
    collapsed: false,
    items: [{ type: 'autogenerated', dirName: 'knifes' }],
  },
];

const EN_SIDEBAR = [
  // Minimal placeholder; add your EN docs later
  // If you create docs/en/index.md with id: KNIFE_HOME, you can switch to:
  // { type: 'doc', id: 'KNIFE_HOME', label: '🏠 Home' },
];

const sidebars: SidebarsConfig =
  LOCALE === 'en'
    ? { defaultSidebar: EN_SIDEBAR }
    : { defaultSidebar: SK_SIDEBAR };

export default sidebars;
