import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'en/index',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'en/getting-started/index',
      },
      items: [],
    },
    {
      type: 'category',
      label: '🔧 Hardware',
      link: {
        type: 'doc',
        id: 'en/hardware/index',
      },
      items: [],
    },
    {
      type: 'category',
      label: '⚡ Features',
      link: {
        type: 'doc',
        id: 'en/features/index',
      },
      items: [],
    },
    {
      type: 'category',
      label: '💻 Architecture',
      link: {
        type: 'doc',
        id: 'en/architecture/index',
      },
      items: [],
    },
    {
      type: 'category',
      label: '7DS Strategy',
      link: {
        type: 'doc',
        id: 'en/7ds/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'en/7ds',
        },
      ],
    },
    {
      type: 'doc',
      id: 'en/testing/index',
      label: '🧪 Testing',
    },
  ],
};

export default sidebars;
