// sidebars.ts
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // Domov (existuje ako docs/sk/index.md => id: 'sk/index')
    { type: 'doc', id: 'sk/index', label: '🏠 Domov' },

    // 7Ds (autogen z docs/sk/7Ds)
    {
      type: 'category',
      label: '7Ds',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'sk/7Ds' }],
    },

    // KNIFES (autogen z docs/sk/knifes)
    {
      type: 'category',
      label: 'KNIFES',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'sk/knifes' }],
    },
  ],
};

export default sidebars;